[package]
name = "sdk-cds"
version = "0.1.0"
authors = ["Benjamin Coenen <benjamin.coenen@corp.ovh.com>"]
edition = "2018"

[dependencies]
reqwest = "0.9.8"
serde = "1.0.0"
serde_derive = "1.0.0"
serde_json = "1.0.0"
http = "0.1.15"
